### PR TITLE
CU-2v6w6dw_re--namespace-from-vethvetheon-to-pixelatedstudios_Connor-Crawford

### PR DESCRIPTION
**Pull request by LyrinoxTechnologies**
New PR for ClickUp tracking

### CODE REVIEW

**Comment by VetheonDevelops** [comment]
Task linked: [CU-2v6w6dw re- namespace from veth.vetheon to pixelated.studios](https://app.clickup.com/t/2v6w6dw)

**Comment by NightSling** [comment]
@VetheonGames It'd be best if we follow the java naming principle and refactor packages to "net.pixelatedstudios.SurvivalPlus"

**Comment by VetheonDevelops** [comment]
> @VetheonGames It'd be best if we follow the java naming principle and refactor packages to "net.pixelatedstudios.SurvivalPlus"

I tried to refactor with IntelliJ but I really don't understand how to do so, which means it requires me to manually rename the namespace.

If you know how to make IntelliJ refactor the whole source successfully, be my guest.

Otherwise, I'll get to it when I'm done with the website

**Review by expxx — DISMISSED** [review]
Tested it on a server, looks all good. 

**NOTE:** Only tested the loading process, nothing else. I can test more when I get home.

**Comment by VetheonDevelops** [comment]
> Tested it on a server, looks all good. 
> 
> **NOTE:** Only tested the loading process, nothing else. I can test more when I get home.

Going to wait for either Daysling to refactor to adhere to naming convention or for me to get around to it before we merge.

**Comment by NightSling** [comment]
I'll get the refactor done!

**Review by NightSling — APPROVED** [review]
GL!

**Comment by VetheonDevelops** [comment]
@NightSling Please sign your commits.

**Comment by NightSling** [comment]
> @NightSling Please sign your commits.

Mine's are signed! It's your first one.

**Pull request merged**
