### PR TITLE
Created the working mechanism of temperature for scoreboard support

### PR DESCRIPTION
**Pull request by NightSling**
Testing Yet to be done, Please review first ;)

### CODE REVIEW

**Comment by VetheonDevelops** [comment]
Task linked: [CU-3kdayc8 Add Temperature to Scoreboard](https://app.clickup.com/t/3kdayc8)

**Review by LyrinoxTechnologies — CHANGES_REQUESTED** [review]
PR is for old 4.0.7 codebase. PR can't be accepted until it's using the newest codebase

PR changed .idea config to use JDK 1.8. It needs to use JDK 17+

**Comment by NightSling** [comment]
> PR is for old 4.0.7 codebase. PR can't be accepted until it's using the newest codebase
> 
> PR changed .idea config to use JDK 1.8. It needs to use JDK 17+

It seems like pom.xml's version didn't get updated for the 8th minor build nor in main and in tag version 8 beta. I'll link another issue and assign it to the same PR

**Review by LyrinoxTechnologies — APPROVED** [review]
Looks good to me. Approved.

**Pull request merged**
